### ISSUE TITLE
应用返回时崩溃

### ISSUE THREAD

**Issue by DuHeng29** [Notsfsssf/pixez-flutter#792]
在“任意界面”使用侧滑返回就会触发。报错：
[ 2024-09-24T01:15:51.187    10456: 12056: 12056 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.perol.pixez, PID: 12056
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by Notsfsssf** [comment]
已经定位到是hyperos近期版本的问题，如果你用chrome也是一样的效果，我会在下个版本考虑去掉`enableOnBackInvokedCallback`
